# Generated by Django 2.2.4 on 2019-10-31 04:36

from django.db import migrations, models
import django_countries.fields
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=256, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_area',
            field=models.CharField(blank=True, max_length=128, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_area',
            field=models.CharField(blank=True, max_length=128, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Given name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, unique=True, verbose_name='电子邮件'),
        ),
    ]
