# Generated by Django 2.2.6 on 2020-01-31 05:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20200129_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Phone number'),
        ),
    ]
