# Generated by Django 2.2.6 on 2020-02-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20200131_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pinyin',
            field=models.TextField(blank=True, max_length=1024, verbose_name='pinyin'),
        ),
    ]
